name: workflow
on: [push]
jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          python-version: '3.10'
      - name: "Install clang-format"
        run: sudo apt install clang-format
      - name: "Run clang-format"
        run: clang-format src/*.cpp src/*.hpp tests/*.cpp --dry-run -Werror
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install dependencies"
        run: sudo apt-get install cmake libyaml-cpp-dev libeigen3-dev libboost-test-dev
      - name: "CMake"
        run: mkdir build
        run: cd build
        run: cmake ..
      - name: "Make"
        run: cd build && make
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: "Install dependencies"
        run: sudo apt-get install cmake libyaml-cpp-dev libeigen3-dev libboost-test-dev
      - name: "Cmake"
        run: mkdir build
        run: cd build
        run: cmake ..
      - name: "Make"
        run: cd build
        run: make
      - name: "Test"
        run: cd build
        run: make test
